### PR TITLE
Update preferences.dtd

### PR DESCRIPTION
**Pull request by ovari**

### CODE REVIEW

**Comment by ovari** [comment]
After further testing, the < ^ and > accessKeys do not work. Please advise once you have merged so they can be fixed with the next beta. Sorry.

**Comment by jmozmoz** [comment]
I have merged all pull request, so you can start again with changes. Could you please put all changes in one pull request? I think you can create a new branch, add all your changes to this branch and then create a pull request for this branch.

**Comment by ovari** [comment]
@jmozmoz Created a branch, added all the changes and created a pull request for that branch about 1 day ago. Did they arrive for you? Also sent you an email with [LibreOffice](https://de.libreoffice.org/) Calc spreadsheet which checked to see that all accessKey associations are unique. Did you receive that email? Thank you

**Comment by jmozmoz** [comment]
Thank you, I received the spread sheet.

**Comment by jmozmoz** [comment]
I pushed a new version to AMO (2.1.3beta4)

**Comment by ovari** [comment]
How long does [CompactHeader](https://addons.mozilla.org/thunderbird/addon/compactheader/) remain in [beta channel](https://addons.mozilla.org/thunderbird/addon/compactheader/#beta-channel) before you change it to the [release channel](https://addons.mozilla.org/thunderbird/addon/compactheader/#detail-relnotes)? Thank you

**Comment by jmozmoz** [comment]
I need to get my automatic tests running again, before I will summit this as main release.

**Pull request merged**
