### PR TITLE
accessKey

### PR DESCRIPTION
**Pull request by ovari**

### CODE REVIEW

**Comment by jmozmoz** [comment]
Thank you for the patch.

**Comment by ovari** [comment]
You are welcome. Are you able to advise:
1. Did you receive the LibreOffice Calc spreadsheet?
2. When the new version will be available for everyone on AMO?
Thank you

**Comment by jmozmoz** [comment]
Yes, I received the spread sheet.

**Comment by jmozmoz** [comment]
I have released the beta version as new release on AMO

**Comment by ovari** [comment]
@jmozmoz Thank you advising that you have released the beta version as a new release on AMO. The final 2 accessKeys have now been uploaded for you.

**Pull request merged**
