### PR TITLE
Update install.rdf

### PR DESCRIPTION
**Pull request by ovari**

### CODE REVIEW

**Comment by jmozmoz** [comment]
Thank you for all these pull requests. Just one question and one remark: 

- Where have you found the information about the translators? For unkown reasons, my addons disappeared at http://babelzilla.org/, so I do not know, how delivered these translations. And nobody is answering there (anymore).

- You can add more than one commit to a pull request, so you do not need to create one per file.

**Comment by jmozmoz** [comment]
A pushed this version as 2.1.3beta2 to AMO

**Comment by ovari** [comment]
Hi Joachim,

Responses to your questions.

* Your translators were shown in your release notes:
https://addons.mozilla.org/en-US/thunderbird/addon/compactheader/versions/?page=1#version-2.0.6

* Still learning how to use GitHub. Do not know how to do more than one commit to a pull request. Can you provide a link which shows how? Thank you

Did you receive the previous email with questions:

1. How can keyboard shortcuts be added to the settings?

2. Where do translations for the AMO hu locale get sent so they will show at:
https://addons.mozilla.org/hu/thunderbird/addon/compactheader/
Similar to:
https://addons.mozilla.org/hu/thunderbird/addon/cardbook/
https://addons.mozilla.org/hu/thunderbird/addon/mailredirect/

Thank you

**Comment by jmozmoz** [comment]
I did not receive an email. At least today/this week.

Do you want to change an existing keyboard shortcut or add a new one? Changing is done by the localisation settings. A new one has to be added in the xul overlay, e.g. https://github.com/jmozmoz/compactheader/blob/master/chrome/CompactHeader/content/compactHeaderOverlay.xul#L34 There the SHIFT+H shortcut for toggling the header is defined. Also have a look at the "accesskey" for menus.

For the translations at AMO, I have to add them in the "addon listing". There is already a French translation: https://addons.mozilla.org/fr/thunderbird/addon/compactheader/

So just add the text here. These are the entries, which can be filled out (with their corresponding English entries):

**Summary**
Add symbol in header plane to switch between compact and expanded view. Options to switch between one or two lines compact view, which buttons should be displayed in header pane. For Thunderbird 36 and older use version 2.0.9 (see version history)

**Description** 
For versions older then Thunderbird 37 use version 2.0.9 (see the version histroy)

Thunderbird does not anymore have the ability to reduce the display size of header pane to one line (as in Thunderbird 2.0). This add-on adds a symbol to compact and expand the message header plane. The compact header view mode can be set to either one or two lines.

A customization dialog can be opened for the toolbar in the header pane (right mouse button context menu) to change the displayed buttons and their style.

The shortcut "SHIFT+h" can be used to toggle between expanded and compact header view.

This add-on integrates the functionality of "RSS Linkify Subject" by Alex Dedul (https://addons.mozilla.org/en-US/thunderbird/addon/1704).

There is also an option to display only the email addresses in the compact header view. Another option enables darkening the message header, if the message pane has focus.

If you want to use the latest version, look for it at the beta channel.

There are several bug reports about a disappearing header pane in the compact header view mode. I could reproduce it if the TB Header Tools Extension is installed at the same time, see http://forums.mozillazine.org/viewtopic.php?p=8543415#p8543415

If you encounter any bug please post information at the support thread at mozillazine:
http://forums.mozillazine.org/viewtopic.php?f=29&t=1405155

**Comment by ovari** [comment]
1. How to add keyboard shortcuts to the Preferences/Settings dialog box:
preferences dialog

2. Will look into translating.

**Comment by jmozmoz** [comment]
In the file https://github.com/jmozmoz/compactheader/blob/master/chrome/CompactHeader/content/preferences.xul
the accesskey attribute has to be added to all relevant checkbox(es): https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/checkbox and if applicable to the radio buttons https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/radio

But of course then all translations have to be updated

**Comment by ovari** [comment]
For uploading to: https://addons.mozilla.org/hu/thunderbird/addon/compactheader/

**Heading**
Tömörített fejléc (CompactHeader)

**Summary**
A fejléc méretének egy vagy két sorral való módosítása. Link témák az RSS csatornákban.

**Description**
GitHub: https://github.com/jmozmoz/compactheader/
Mozillazine: http://forums.mozillazine.org/viewtopic.php?f=29&t=1405155
Fejlesztői csatorna: https://addons.mozilla.org/hu/thunderbird/addon/compactheader/#beta-channel

**Image captions**
One line compact header view Two line compact header view Expanded header view with buttons (without labels) → 
* egysoros tömörített fejléc
* kétsoros tömörített fejléc
* kibővített fejléc nézet gombokkal (címkék nélkül)

Header pane toolbar customization dialog box. Buttons can be dropped onto the header pane toolbar or removed from there. The style of the buttons can be changed or the default set can be restored. → 
Fejléc panel eszköztár testreszabási párbeszédpanel. A gombokat a fejléc panel eszköztárára lehet dobni, vagy onnan eltávolítani. A gombok stílusa megváltoztatható, vagy az alapértelmezett beállítás visszaállítható.

Preference dialog of the add-on. You can access it from the other actions button, the add-on manager or the context menu in the header pane. → 
Tömörített fejléc beállítások

**Comment by ovari** [comment]
Please advise when hu locale of AMO is updated.
https://addons.mozilla.org/hu/thunderbird/addon/compactheader/
Thank you

**Comment by jmozmoz** [comment]
Thank you for all your work. I have uploaded the translation. You should see it now.

**Pull request merged**
